### ISSUE TITLE
CoreImageExtensions-dynamic missing

### ISSUE THREAD

**Issue by daver234** [DigitalMasterpieces/CoreImageExtensions#7]
Hi,

Using Swift Package Manager to load I get CoreImageExtensions-dynamic is missing.  I see it in your package definition but I don't see a URL for this?

Thanks,
Dave

**Comment by frankschlegel** [comment]
Hi Dave,

How do you include the package?
If it should be the dependency of another package, this should do the trick:
```swift
let package = Package(
    dependencies: [
        .package(url: "https://github.com/DigitalMasterpieces/CoreImageExtensions", .upToNextMajor(from: "1.0.0"))
    ],
    targets: [
        .target(
            name: "MyTarget",
            dependencies: [.product(name: "CoreImageExtensions-dynamic", package: "CoreImageExtensions")]
        )
    ]
)
```

If you added the package to your Xcode project, you should be able to see `CoreImageExtensions-dynamic` in the list when adding a library to your target.
